(() => {
 'use strict';
 const workflow=document.body.dataset.workflow;
 const e=s=>L.escape(String(s??''));
 const btn=(text,action,kind='primary')=>L.button(text,action,kind);
 const link=(text,file,params={},kind='secondary')=>`<a class="btn ${kind}" href="${L.href(file,params)}">${e(text)} ${L.icon('arrow')}</a>`;
 const card=(title,body,actions='')=>`<section class="card"><div class="card-head spread"><h2>${title}</h2>${actions}</div><div class="card-body">${body}</div></section>`;
 const note=(title,body,tone='blue')=>L.note(title,body,tone);
 const field=(label,id,value,type='text')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${e(value)}" ${type==='number'?'min="0" step="1"':''}></div>`;
 const source=s=>String(s??'Detectado en plano');
 const rows=()=>L.get('engineering-bom',B.bom.map(r=>({...r})));
 const ruleQuantity=()=>2*(rows().find(r=>r.id==='tm')?.quantity??24);
 const altSaving=()=>2460*(rows().find(r=>r.id==='ct')?.quantity??6);
 const total=()=>rows().reduce((s,r)=>s+r.quantity*r.price,0);
 const p=()=>B.project;
 const alternative=()=>L.get('bom-alternative',{rowId:'ct',brand:'Marca B',specification:'3P · 25 A · bobina 230 V',sku:'MB-CT325',approved:false});
 const alternativeFields=()=>`<div class="eng-inline">${field('Marca alternativa (opcional)','alternative-brand-input',alternative().brand)}${field('Especificación alternativa','alternative-spec',alternative().specification)}</div><p class="small muted">Solo el contactor admite alternativa en este ejemplo. Los otros cinco materiales conservan la base.</p><div class="footer-actions">${btn('Guardar alternativa por ítem','alternative-item','secondary')}${btn('Eliminar alternativa opcional','alternative-remove','ghost')}</div>`;
 const done=s=>L.get(s,false);
 const banner=()=>L.get('engineering-message','')?note('Revisá el dato',e(L.get('engineering-message','')),'amber'):'';
 const summarize=()=>`<div class="eng-summary-grid"><div><span class="small muted">Materiales de referencia</span><div class="amount">${L.money(total())}</div><span class="small muted">Sin impuestos ni flete</span></div><div><span class="small muted">Tablero tipo</span><div class="eng-count">×${L.get('plan-multiplier',p().multiplier)}</div><span class="small muted">Sin repetir la detección</span></div><div><span class="small muted">Versión de trabajo</span><div class="amount">${e(p().revision)}</div><span class="small muted">Datos ficticios · 30/09/2026</span></div></div>`;
 const stageFooter=(text,action,back='')=>`<div class="footer-actions">${back?btn('Volver',back,'secondary'):''}<span class="muted small">${workflow==='alternatives'||workflow==='revisions'?'Propuesta funcional · requiere implementación':'Simulación local · no envía archivos ni pedidos'}</span>${btn(text,action)}</div>`;
 function plan(selected='tm') {
  return `<div class="eng-plan"><svg viewBox="0 0 650 380" role="img" aria-label="Esquema ficticio TS-1P. Interruptores, diferencial y contactor unidos por barras; símbolo Q7 seleccionado."><rect width="650" height="380" fill="#f9fbfd"/><g font-family="Arial,sans-serif" font-size="12" fill="#55667f"><text x="25" y="30">TS-1P · TABLERO SECCIONAL</text><text x="25" y="49">Esquema ilustrativo · no es un plano de ingeniería</text></g><g stroke="#7689a3" stroke-width="1.5" fill="none"><path d="M320 65V95M90 115H570M140 115V167M250 115V167M360 115V167M470 115V167M140 205V275M250 205V275M360 205V275M470 205V275M130 177l20 22M240 177l20 22M350 177l20 22M460 177l20 22"/><path d="M310 93l20 22M320 115V130"/><circle cx="140" cy="225" r="11"/><path d="M130 225H150M139 273l16 20M250 275l15 20M360 275l15 20M470 275l15 20"/></g><g font-family="Arial,sans-serif" font-size="12" fill="#263c5a"><text x="342" y="94">40A · 4P</text><text x="160" y="188">${selected==='ct'?'K1':'Q7'}</text><text x="160" y="207">${selected==='ct'?'3P · 25A':'16A · Curva C'}</text><text x="160" y="227">${selected==='ct'?'Bobina por confirmar':'6kA · 2P'}</text><text x="273" y="187">Q8</text><text x="383" y="187">Q9</text><text x="493" y="187">Q10</text><text x="115" y="325">C1 · iluminación</text><text x="280" y="325">C2 · tomas</text><text x="440" y="325">C3 · control</text></g><rect class="selected" x="117" y="151" width="125" height="101" rx="7"/><g fill="#2563eb"><circle cx="126" cy="159" r="3"/><circle cx="232" cy="243" r="3"/></g></svg>${link('Explorar tablero conceptual','d-panel.html',{variant:'visual'})}</div>`;
 }
 function bomTable(edit=false){return L.table(['Material / especificación','Origen','Dibujada','A comprar','Estado'],rows().map(r=>[ `<strong>${e(r.material)}</strong><div class="small muted">${e(r.specification)}</div>`,L.badge(source(r.source),r.id==='cab'?'amber':'gray'),r.qtyPlan==null?'—':e(r.qtyPlan),edit?`<input class="eng-table-input" aria-label="Cantidad a comprar de ${e(r.material)}" data-bom-id="${e(r.id)}" type="number" min="0" step="1" value="${r.quantity}">`:`<strong>${L.num(r.quantity)}</strong> ${e(r.unit)}`,L.badge(r.id==='ct'&&!done('essentials-complete')?'Origen por confirmar':'Atributos completos',r.id==='ct'&&!done('essentials-complete')?'amber':'green')]));}
 function reviewCard(ctx){return card('Una especificación necesita tu criterio',`<div class="row spread">${L.badge('1 pendiente','amber')}<span class="small mono">TS-1P · símbolo K1</span></div><h3>Contactor · 3P · 25 A</h3><p class="muted">El dibujo indica los polos y la corriente. Falta la tensión de la bobina para identificar un producto.</p>${note('Sin coincidencia segura','No se asigna un SKU hasta completar el atributo esencial.','amber')}<div class="eng-context"><span class="small muted">Origen de evidencia</span><p>Texto junto al símbolo: «3P · 25 A». Tensión de bobina: sin dato.</p></div><div class="footer-actions">${btn('Ver fuente','source')}${ctx.variant==='expert'?btn('Completar atributo','correct','secondary'):''}</div>`);}
 const renderers={
 projects(ctx){
  if(ctx.stage==='create')return card('Un proyecto, un contexto técnico',`${banner()}<div class="grid equal">${field('Nombre del proyecto','project-name',L.get('project-name',p().name))}${field('Fecha objetivo','project-due','2026-10-20','date')}</div><div class="field"><label for="entry-source">¿Con qué comenzás?</label><select id="entry-source"><option value="plans">Planos DXF o PDF · existente</option><option value="bom">BOM propio · propuesta</option></select></div>${note('Separación de datos','La galería guarda solo una simulación en este navegador. Cada cuenta real conserva sus proyectos privados.')} ${stageFooter('Crear proyecto de demostración','create-project','portfolio')}`);
  if(ctx.stage==='ready')return card('Proyecto preparado',`<div class="row">${L.badge('Creado en la demo','green')}<span class="mono">${p().code}</span></div><h3>${e(L.get('project-name',p().name))}</h3><p class="muted">Elegí el punto de entrada de tu trabajo.</p><div class="grid equal">${link('Cargar planos','d-intake.html',{stage:'upload',variant:'guided'},'primary')}${link('Usar un BOM existente · propuesta','d-intake.html',{stage:'upload',variant:'expert'})}</div>`);
  if(ctx.variant==='expert')return `${card('Proyectos · decisiones pendientes',`${L.table(['Proyecto','Versión','Estado técnico','Materiales de referencia','Siguiente tarea'],[[`<strong>${e(L.get('project-name',p().name))}</strong><div class="small muted">${p().code} · ${p().due}</div>`,p().revision,L.badge(done('essentials-complete')?'Revisado':'1 revisión pendiente',done('essentials-complete')?'green':'amber'),L.money(total()),link('Abrir revisión','d-review.html',{stage:'uncertainty',variant:'expert'},'primary')]])}<div class="footer-actions">${btn('Crear proyecto','create')}${link('Importar BOM propio · propuesta','d-intake.html',{variant:'expert'})}${link('Abrir cotización','d-quote.html',{variant:'expert'})}</div>`)}${card('Acceso directo al trabajo',`<div class="grid three">${link('Consolidado y cantidades','d-bom.html',{variant:'expert'})}${link('Diferencias de revisión','d-revisions.html',{variant:'expert'})}${link('Pedidos enviados','d-orders.html',{variant:'expert'})}</div>`)}`;
  return `<div class="eng-hero"><div class="eng-kicker">Ingeniería · espacio de trabajo</div><h2>De cada plano, una decisión de compra.</h2><p class="muted">Volvé a tus revisiones, completá datos técnicos y encontrá los materiales que necesita la obra.</p>${btn('Nuevo proyecto','create')}</div><div class="grid two">${card('Proyecto activo',`<div class="eng-project-card"><div>${L.badge('En revisión','amber')}<h3>${e(L.get('project-name',p().name))}</h3><p class="muted">${p().code} · versión ${p().revision} · objetivo ${p().due}</p></div>${link('Continuar revisión','d-review.html',{stage:'uncertainty',variant:ctx.variant},'primary')}</div><div class="divider"></div>${summarize()}<div class="footer-actions">${link('Ver BOM','d-bom.html',{variant:'expert'})}${link('Ver pedidos','d-orders.html',{variant:'expert'})}</div>`)}${card('Tu próxima decisión',`<div class="eng-step-num">1</div><h3>Completar tensión de bobina</h3><p class="muted">Un dato pendiente bloquea el matching de 6 contactores.</p>${link('Resolver con evidencia','d-review.html',{stage:'source',variant:'guided'})}`)}</div>`;
 },
 intake(ctx){
  if(ctx.stage==='upload'&&ctx.variant==='expert')return `<div class="grid two">${card('Partir de un BOM ya contado',`${L.badge('Propuesta · segmento experto','blue')}<h3>Tu conteo es el punto de partida.</h3><p class="muted">Importación guiada de una lista propia. Los mismos seis materiales de Aurora se usan en todos los recorridos.</p><div class="eng-file">${L.icon('file')}<h3>Aurora-listado-R03.xlsx</h3><p class="small muted">Ejemplo ficticio · 6 líneas · unidad y cantidad</p>${btn('Validar el listado de ejemplo','import-bom')}</div>${note('Control técnico','La importación conserva tu descripción. No reemplaza atributos faltantes por una inferencia silenciosa.')}<div class="footer-actions">${link('Prefiero cargar planos','d-intake.html',{variant:'guided',stage:'upload'})}</div>`)}${card('Qué conserva la importación',`<div class="checklist"><p>✓ Cantidades originales</p><p>✓ Material y especificación</p><p>✓ Marca solicitada</p><p>✓ Datos por completar</p></div>${note('Privacidad','En esta demo ningún archivo sale del navegador. El importador real de BOM es una propuesta.')}`)}</div>`;
  if(ctx.stage==='upload')return card('Cargar los planos de la obra',`${banner()}<div class="eng-file">${L.icon('file')}<h3>TS-1P · tablero tipo</h3><p>DXF o PDF · tabla de referencia opcional</p><div class="field"><label for="plan-file">Elegir archivo local (solo nombre, sin envío)</label><input id="plan-file" class="eng-file-input" type="file" accept=".dxf,.pdf,.dwg"><div class="eng-file-choice">${btn('Elegir archivo','choose-file','secondary')}<span id="plan-file-name" class="small muted">Ningún archivo seleccionado</span></div></div>${btn('Usar plano de ejemplo','sample-plan','secondary')}</div>${note('¿Tenés un DWG?','El procesamiento directo se evalúa para Sprint 5. Usá DXF o PDF como alternativa actual.','amber')}<div class="eng-inline">${field('Nombre del tablero','board-name','TS-1P')}<div class="field"><label for="plan-format">Formato del ejemplo</label><select id="plan-format"><option>DXF</option><option>PDF</option></select></div></div>${stageFooter('Preparar tablero tipo','upload-next')}`);
  if(ctx.stage==='crop')return `<div class="grid two">${card('Delimitar el tablero tipo',`${plan(workflow==='review'?'ct':'tm')}<div class="footer-actions">${btn('Seleccionar esta zona','select-zone','secondary')}<span class="small muted">${done('zone-selected')?'Zona TS-1P seleccionada':'Seleccioná una zona antes de continuar'}</span></div>`)}${card('Cuántas veces se repite',`${banner()}${field('Repeticiones del tablero TS-1P','multiplier',L.get('plan-multiplier',3),'number')}<p class="muted small">Contá el tablero dibujado una vez. La compra consolida las repeticiones; gabinete y seccionadores agregados al proyecto conservan su propia cantidad.</p>${note('Ahorro de procesamiento','Cambiar repeticiones no ejecuta de nuevo la detección.')}<div class="field"><label for="reference">Tabla de referencia</label><select id="reference"><option value="none">Sin tabla · opcional</option><option value="demo">Tabla del ejemplo · solo demostración</option></select></div>${stageFooter('Enviar a la cola de demostración','enqueue','upload')}`)}</div>`;
  if(ctx.stage==='queue')return `<div class="grid two">${card('Procesamiento en segundo plano',`<div class="row spread">${L.badge(done('queue-finished')?'Completado':'En cola','blue')}<span class="small mono">TS-1P · intento 1</span></div><h3>Podés seguir trabajando.</h3><p class="muted">La detección se procesa por turnos. Esta vista simula el resultado y no llama a una IA.</p><div class="progress"><div style="width:${done('queue-finished')?100:24}%"></div></div><div class="timeline"><p>Archivo preparado</p><p>Tablero tipo: ${L.get('plan-multiplier',3)} repeticiones</p><p>${done('queue-finished')?'Resultado listo para revisar':'Esperando procesamiento'}</p></div>${stageFooter('Simular resultado disponible','queue-complete','crop')}`)}${card('Antes de comprar',`<h3>Una revisión pendiente</h3><p class="muted">El contactor tiene polos y corriente. La tensión de su bobina requiere confirmación técnica.</p>${link('Editar sin IA','d-bom.html',{stage:'edit',variant:'expert'})}`)}</div>`;
  return card(ctx.variant==='expert'?'BOM importado para revisar':'Detección lista para revisar',`${L.badge('Resultado de demostración','green')}${summarize()}<p class="muted">La misma lista inicial está disponible para comparar el recorrido guiado y el espacio experto.</p>${link('Revisar los componentes','d-review.html',{stage:'uncertainty',variant:ctx.variant},'primary')}`);
 },
 review(ctx){
  if(ctx.stage==='uncertainty')return ctx.variant==='expert'?`<div class="grid equal">${card('Plano y evidencia',plan())}${reviewCard(ctx)}</div>${card('Lista vinculada',bomTable())}`:`<div class="grid two">${reviewCard(ctx)}${card('Revisión enfocada',`<div class="eng-count">1</div><h3>Decisión técnica pendiente</h3><p class="muted">6 contactores de la obra quedan sin producto hasta revisar el atributo esencial.</p><div class="divider"></div><p class="small muted">Contexto conservado: ${p().code} · ${p().revision} · TS-1P</p>${link('Abrir revisión experta','d-review.html',{stage:'uncertainty',variant:'expert'})}`)}</div>`;
  if(ctx.stage==='source')return `<div class="grid two">${card('Evidencia del plano',`${plan(workflow==='review'?'ct':'tm')}<div class="eng-context"><strong>Qué dice el dibujo</strong><p>3P · 25 A. Sin indicación de tensión de bobina.</p></div>`)}${card('Identificación pendiente',`<h3>Contactor K1</h3><p class="muted">No hay información suficiente para fijar un SKU comercial.</p><div class="eng-pill-list">${L.badge('25 A','gray')}${L.badge('3P','gray')}${L.badge('Bobina: falta dato','amber')}</div>${note('Criterio experto','El catálogo de la base R03 propone 230 V. Confirmá ese dato con el pliego; el origen de la detección no se declara validado hasta tu revisión. Un valor diferente requiere una nueva revisión técnica.','amber')}${stageFooter('Completar con fuente','correct','uncertainty')}`)}</div>`;
  if(ctx.stage==='correct')return `<div class="grid two">${card('Completar el atributo esencial',`${banner()}<div class="field"><label for="coil-voltage">Tensión de la bobina</label><select id="coil-voltage"><option value="">Seleccionar valor confirmado</option><option value="230 V">230 V CA</option></select></div>${field('Fuente de la corrección','correction-source',L.get('correction-source','Pliego de ejemplo R03 · cláusula 4.2'))}<div class="field"><label for="correction-scope">Alcance de la corrección</label><select id="correction-scope"><option value="all">Todos los iguales · 6 unidades del proyecto</option><option value="one">Un símbolo · genera revisión de los restantes</option></select></div><label class="eng-checkbox"><input type="checkbox" id="technical-confirmation"><span>Revisé la fuente y confirmo este dato para el alcance elegido.</span></label>${note('Trazabilidad','El atributo queda registrado como corrección manual, con su fuente. No se reetiqueta como detección IA.')} ${stageFooter('Guardar corrección','save-correction','source')}`)}${card('Impacto del cambio',`<h3>6 contactores · ARS 246.000 de referencia</h3><p class="muted">Completar el dato habilita una búsqueda por tipo y atributos. El proveedor todavía debe confirmar stock, producto y precio.</p>${plan(workflow==='review'?'ct':'tm')}`)}</div>`;
  return card('Revisión registrada',`${L.badge(done('essentials-complete')?'Atributo completado':'Revisión parcial',done('essentials-complete')?'green':'amber')}<h3>${done('essentials-complete')?'El BOM puede buscar coincidencias':'Quedan símbolos por confirmar'}</h3><p class="muted">${done('essentials-complete')?'Tensión de bobina: '+e(L.get('coil-voltage','230 V'))+' · fuente: '+e(L.get('correction-source','Pliego R03')):'La corrección de un símbolo no se aplica silenciosamente a todos los demás.'}</p><div class="footer-actions">${link('Continuar al BOM','d-bom.html',{stage:'consolidated',variant:ctx.variant},'primary')}${!done('essentials-complete')?btn('Revisar los restantes','correct','secondary'):''}</div>`);
 },
 bom(ctx){
  if(ctx.stage==='edit')return `<div class="grid two">${card('Editar cantidades a comprar',`${banner()}${bomTable(true)}<p class="small muted">Las cantidades editadas se conservan en el navegador. La cantidad dibujada queda como evidencia de origen.</p>${stageFooter('Guardar cantidades','save-bom','consolidated')}`)}${card('Atributos esenciales',`<h3>Contactor 3P · 25 A</h3><p class="muted">${done('essentials-complete')?'Tensión confirmada: '+e(L.get('coil-voltage','230 V')):'Tensión de origen por confirmar; catálogo: 230 V.'}</p>${link('Editar con evidencia','d-review.html',{stage:'correct',variant:ctx.variant})}<div class="divider"></div><h3>Marca y gama</h3><p class="small muted">La marca es distinta del proveedor. Conservar restricciones del pliego evita equivalencias comerciales inválidas.</p><div class="field"><label for="bom-brand">Marca del ejemplo</label><select id="bom-brand"><option>Marca A</option><option>Marca B</option><option>Sin preferencia</option></select></div>${btn('Guardar preferencia de la demo','save-brand','secondary')}`)}</div>`;
  if(ctx.stage==='rules')return `<div class="grid two">${card('Accesorios sugeridos por regla',`${L.badge('Propuesta · necesita validación','blue')}<h3>Terminales para el tablero tipo</h3><p class="muted">Ejemplo de regla de empresa: 2 terminales por termomagnética. No proviene de la detección del plano.</p><div class="eng-summary-grid"><div><span class="small muted">Base del ejemplo</span><div class="amount">${rows().find(r=>r.id==='tm').quantity} ITM</div></div><div><span class="small muted">Regla visible</span><div class="amount">× 2</div></div><div><span class="small muted">Sugerencia</span><div class="amount">${ruleQuantity()} terminales</div></div></div>${note('Sin cálculo eléctrico automático','El supervisor debe elegir la sección y confirmar que la regla corresponde a esta obra.','amber')}<div class="field"><label for="rule-section">Sección confirmada del terminal</label><select id="rule-section"><option value="">Seleccionar</option><option value="1.5">1,5 mm²</option><option value="2.5">2,5 mm²</option></select></div><label class="eng-checkbox"><input id="rule-confirm" type="checkbox"><span>Apruebo esta regla para el ejemplo y revisé la sección.</span></label>${banner()}${stageFooter('Agregar como línea derivada','apply-rule','consolidated')}`)}${card('Procedencia protegida',`<div class="timeline"><p>Detectado: 24 termomagnéticas</p><p>Derivado: regla terminales ×2</p><p>Validación: Elena Ruiz · demo</p><p>Vinculación comercial: pendiente</p></div><p class="muted small">La nueva línea no tiene precio ni SKU confirmado; queda pendiente de cotización.</p>`)} </div>`;
  if(ctx.stage==='ready')return card(done('bom-saved')?'BOM guardado para cotizar':'Preparar BOM para cotizar',`${L.badge(done('bom-saved')?'Versión de trabajo guardada':'Guardado pendiente',done('bom-saved')?'green':'amber')}<h3>${e(p().name)}</h3>${summarize()}${done('rule-applied')?note('Una línea derivada pendiente',`${ruleQuantity()} terminales necesitan producto y precio confirmado antes de una compra completa.`,'amber'):''}<p class="muted">La cotización conserva un snapshot; cambios posteriores no alteran las solicitudes enviadas.</p><div class="footer-actions">${link('Comparar proveedores','d-quote.html',{variant:ctx.variant==='guided'?'guided':'expert'},'primary')}${link('Definir BOM alternativo','d-alternatives.html',{variant:ctx.variant})}</div>`);
  return `${summarize()}${!done('essentials-complete')?note('Una línea no tiene coincidencia segura','La tensión de bobina no está confirmada en el dato de origen. El catálogo propone 230 V; revisá la fuente o conservá el pendiente.','amber'):note('Atributos esenciales revisados','La búsqueda utiliza igualdad técnica; el catálogo sigue siendo un precio de referencia.')}<div class="${ctx.variant==='guided'?'grid two':'stack'}">${card('BOM consolidado · seis materiales',`${bomTable()}${done('rule-applied')?`<div class="eng-context">${ruleQuantity()} terminales · sección ${e(L.get('rule-section',''))} mm² · derivados por regla · sin precio</div>`:''}<div class="footer-actions">${btn('Editar cantidades','edit','secondary')}${btn(done('essentials-complete')?'Guardar y continuar':'Revisar dato pendiente',done('essentials-complete')?'bom-ready':'review-blocker')}</div>`)}${card('Siguiente decisión',`<h3>${done('essentials-complete')?'Comparar oferta y disponibilidad':'Completar el contactor'}</h3><p class="muted">${ctx.variant==='guided'?'Un paso a la vez: validar, cotizar y elegir.':'Podés recorrer todas las líneas y conservar los pendientes visibles.'}</p>${btn('Reglas de accesorios · propuesta','rules','secondary')}<div class="divider"></div>${link('Visualizar relaciones del tablero','d-panel.html',{variant:'visual'})}`)}</div>`;
 },
 alternatives(ctx){
  if(ctx.stage==='define'&&ctx.variant==='expert')return card('Escenarios del mismo BOM',`${L.badge('Sprint 5 · planificado','blue')}<p class="muted">Compará técnicamente antes de elegir precio o plazo. Conservamos la versión base.</p>${L.table(['Escenario','Materiales','Cantidad / tipo','Restricción','Acción'],[['Base R03',L.money(total()),'6 contactores · 3P · 25 A','Marca A',btn('Abrir comparación','compare','secondary')],['Disponibilidad prioritaria',L.money(total()-altSaving()),'6 contactores · 3P · 25 A','Marca B · aprobación necesaria',btn('Revisar equivalencia','compare')]])}${note('Mismo punto de partida','Recorrido guiado y matriz experta utilizan las mismas seis líneas y cantidades de Aurora. No se modifica la base.')}${alternativeFields()}<div class="footer-actions">${link('Editar condiciones en recorrido guiado','d-alternatives.html',{variant:'guided',stage:'define'})}</div>`);
  if(ctx.stage==='define')return `<div class="grid two">${card('Separar base y alternativa',`${banner()}${L.badge('Sprint 5 · definición pendiente','blue')}<h3>Plan B para el contactor</h3><p class="muted">La alternativa mantiene las cantidades de Aurora y propone otra marca, sujeta al mismo tipo y atributos esenciales.</p>${field('Nombre del escenario','alternative-name',L.get('alternative-name','Disponibilidad prioritaria'))}${alternativeFields()}<div class="field"><label for="alternative-reason">Motivo</label><select id="alternative-reason"><option value="stock">Disponibilidad / entrega</option><option value="cost">Costo de compra</option><option value="brand">Equivalencia de marca</option></select></div>${note('No cambia la base','La alternativa es un escenario. No modifica un pedido enviado ni elimina la restricción de marca del pliego.')} ${stageFooter('Comparar dos escenarios','alternative-define')}`)}${card('Misma necesidad técnica',`<h3>Contactor · 3P · 25 A</h3><p class="muted">Bobina: ${done('essentials-complete')?e(L.get('coil-voltage','230 V')):'por confirmar'}</p><div class="eng-trace"><span>Plano</span>${L.icon('arrow')}<span>BOM base</span>${L.icon('arrow')}<span>Escenario alternativo</span></div>`)}</div>`;
  if(ctx.stage==='compare')return `${note('Comparación del mismo BOM','Los números son escenarios ficticios sobre las mismas cantidades. No representan una oferta confirmada.')}<div class="grid equal">${card('Base · Marca A',`<h3>${L.money(total())}</h3><p class="muted">12 días de referencia · restricciones actuales</p>${bomTable()}`)}${card('Alternativa · Marca B',`<h3>${L.money(total()-altSaving())}</h3><p class="muted">7 días simulados · solo sustituye 6 contactores</p>${L.table(['Dato','Base','Alternativa'],[['Contactor','Marca A',e(alternative().brand)],['Cantidad','6','6'],['Especificación',e(B.bom.find(r=>r.id==='ct').specification),e(alternative().specification)],['Tensión bobina',done('essentials-complete')?e(L.get('coil-voltage','230 V')):'Pendiente',done('essentials-complete')?e(L.get('coil-voltage','230 V')):'Pendiente'],['Referencia / unidad',L.money(41000),L.money(38540)]])}<div class="eng-validation">La compatibilidad técnica requiere validación; stock y plazo requieren respuesta del proveedor.</div>${stageFooter('Revisar restricciones','approve','define')}`)}</div>`;
  if(ctx.stage==='approve')return card('Aprobación técnica del escenario',`${banner()}<h3>${e(L.get('alternative-name','Disponibilidad prioritaria'))}</h3><label class="eng-checkbox"><input type="checkbox" id="alternative-tech"><span>Verifiqué corriente, polos, tensión, familia y compatibilidad. ${!done('essentials-complete')?'Primero falta confirmar tensión de bobina.':''}</span></label><div class="divider"></div><label class="eng-checkbox"><input type="checkbox" id="alternative-brand"><span>El pliego admite esta marca y la alternativa no viola un convenio de exclusividad.</span></label>${field('Fuente / responsable de aprobación','alternative-source','Revisión técnica de ejemplo · Elena Ruiz')}${note('La aprobación no adjudica','Preparar un escenario no compra materiales. La cotización final permanece bajo confirmación del proveedor.')}<div class="footer-actions">${link('Completar atributo pendiente','d-review.html',{stage:'correct',variant:'expert'})}${btn('Aprobar escenario de la demo','approve-alternative')}</div>`);
  return card(done('alternative-approved')?'Alternativa aprobada y trazable':'Alternativa pendiente de aprobación',`${L.badge(done('alternative-approved')?'Aprobada en demo':'Aprobación pendiente',done('alternative-approved')?'green':'amber')}<h3>Conservamos la base y el motivo del cambio.</h3><div class="eng-trace"><span>${p().revision} · base</span>${L.icon('arrow')}<span>Alternativa A01</span>${L.icon('arrow')}<span>Cotización por confirmar</span></div><div class="eng-context"><strong>Variante exacta para la solicitud:</strong> ${e(alternative().brand)} · ${e(alternative().specification)} · SKU de ejemplo ${e(alternative().sku)}</div><p class="muted">Fuente: ${e(L.get('alternative-source','Sin aprobación registrada'))}</p>${link('Cotizar el escenario seleccionado','d-quote.html',{variant:ctx.variant==='guided'?'guided':'expert',scenario:'alternative'},'primary')}`);
 },
 revisions(ctx){
  if(ctx.stage==='diff'&&ctx.variant==='expert')return card('Comparación técnica de versiones',`${L.badge('Propuesta · control de revisiones','blue')}${L.table(['Material','R03','R04 propuesta','Diferencia','Referencia adicional'],rows().map(r=>[e(r.material),L.num(r.quantity),L.num(r.quantity+(r.id==='tm'?3:0)),r.id==='tm'?L.badge('+3 unidades de proyecto','amber'):'Sin cambio',r.id==='tm'?L.money(54000):'—']))}${note('Snapshot anterior protegido','La diferencia no vuelve a multiplicar el tablero tipo ni altera el pedido ya enviado.')}<div class="footer-actions">${btn('Resolver los cambios','resolve')}${link('Ver costo y margen','d-commercial.html',{variant:'expert'})}</div>`);
  if(ctx.stage==='diff')return `<div class="grid two">${card('Cambió la necesidad de compra',`${L.badge('Propuesta · revisión versionada','blue')}<h3>R03 → R04 · tomas adicionales</h3><p class="muted">Una revisión nueva suma 3 termomagnéticas por proyecto. La cotización anterior conserva su snapshot.</p><div class="eng-diff"><p>Termomagnética 2P 16A: <del>24 unidades</del> ${L.icon('arrow')} <ins>27 unidades</ins></p></div><div class="eng-context">Origen: nota de cambio del ejemplo R04. No se aplica el multiplicador otra vez: la cantidad es adicional de proyecto.</div>${stageFooter('Resolver el cambio','resolve')}`)}${card('Qué permanece',`<div class="checklist"><p>✓ BOM R03 preservado</p><p>✓ Oferta anterior sin cambios</p><p>✓ Cantidad dibujada conservada</p><p>✓ Incremento registrado por separado</p></div>${link('Consultar pedido existente','d-orders.html',{variant:'expert'})}`)}</div>`;
  if(ctx.stage==='resolve')return card('Decidir cómo aplicar la revisión',`${banner()}<div class="field"><label for="revision-choice">Tratamiento de la revisión</label><select id="revision-choice"><option value="additional">Preparar un adicional de 3 unidades</option><option value="replace">Reemplazar versión de trabajo, sin alterar pedidos enviados</option><option value="discard">Descartar la nota de cambio del ejemplo</option></select></div>${field('Motivo de la decisión','revision-reason','Pedido de revisión del cliente · ejemplo R04')}<label class="eng-checkbox"><input id="revision-confirm" type="checkbox"><span>Confirmo que el cambio está autorizado para esta obra.</span></label>${note('Edición concurrente','El estado “conflicto” permite ensayar el caso en que otra persona guardó primero. Volvé a comparar antes de aplicar.','amber')}${stageFooter('Calcular impacto','revision-resolve','diff')}`);
  if(ctx.stage==='impact')return `<div class="grid equal">${card('Impacto previsto',`<div class="eng-summary-grid"><div><span class="small muted">Material adicional</span><div class="amount">${L.get('revision-choice','additional')==='discard'?0:3} ITM</div></div><div><span class="small muted">Referencia</span><div class="amount">${L.money(L.get('revision-choice','additional')==='discard'?0:54000)}</div></div><div><span class="small muted">Impuestos / flete</span><div class="amount">Por definir</div></div></div><p class="muted">No se presupone stock, ni se reemplaza un precio ya enviado.</p>${stageFooter('Registrar revisión aprobada','revision-approve','resolve')}`)}${card('Mantener rentabilidad',`<h3>El adicional también tiene costo de trabajo.</h3><p class="muted">Podés incluir horas, reserva y gastos antes de preparar la propuesta comercial.</p>${link('Explorar costo y margen','d-commercial.html',{variant:'expert'})}`)}</div>`;
  return card(done('revision-approved')?'Cambio registrado':'Revisión pendiente de registro',`${L.badge(done('revision-approved')?'Revisión R04 · demo':'Registro pendiente',done('revision-approved')?'green':'amber')}<h3>${L.get('revision-choice','additional')==='discard'?'Nota descartada con motivo':'Adicional preparado: 3 unidades'}</h3><p class="muted">${e(L.get('revision-reason','Solicitud R04'))}</p>${note('Historial conservado','R03 y sus ofertas permanecen intactos. R04 requiere una nueva cotización o propuesta adicional.')}<div class="footer-actions">${link('Cotizar adicional','d-quote.html',{variant:'expert',scenario:'additional'},'primary')}${link('Ver historial de solicitudes','d-orders.html',{variant:'expert'})}</div>`);
 }
 };
 const definitions={projects:{title:'Proyectos',subtitle:'Una obra, sus planos y todas las decisiones de compra.',status:'Existe · experiencia refinada',steps:[['portfolio','Proyectos'],['create','Crear'],['ready','Continuar']]},intake:{title:'Preparar los planos',subtitle:'Un tablero tipo se procesa una sola vez.',status:'Existe · experiencia refinada',steps:[['upload','Entrada'],['crop','Tablero tipo'],['queue','Procesamiento'],['ready','Resultado']]},review:{title:'Revisión técnica',subtitle:'Completá lo que falta sin ocultar incertidumbre.',status:'Existe · experiencia refinada',steps:[['uncertainty','Pendientes'],['source','Fuente'],['correct','Corrección'],['approved','Resultado']]},bom:{title:'BOM del proyecto',subtitle:'Cantidades, atributos y procedencia antes de cotizar.',status:'Existe · experiencia refinada',steps:[['consolidated','Consolidado'],['edit','Editar'],['rules','Reglas · propuesta'],['ready','Cotizar']]},alternatives:{title:'BOM alternativo',subtitle:'Compará escenarios sin perder la base.',status:'Sprint 5 · planificado',steps:[['define','Definir'],['compare','Comparar'],['approve','Validar'],['trace','Cotizar']]},revisions:{title:'Revisiones del proyecto',subtitle:'El cambio tiene un origen y un costo visible.',status:'Propuesta · validar',steps:[['diff','Diferencias'],['resolve','Resolver'],['impact','Impacto'],['approved','Registrar']]}};
 const read=id=>document.getElementById(id)?.value?.trim()??'';
 const checked=id=>document.getElementById(id)?.checked??false;
 const error=text=>{L.save('engineering-message',text);L.refresh();};
 const advance=stage=>{L.save('engineering-message','');L.go({stage});};
 function onAction(action,el,ctx){
  if(action==='choose-file'){document.getElementById('plan-file')?.click();return;}
  if(action==='create-project'){if(!read('project-name'))return error('Ingresá un nombre para identificar el proyecto.');L.save('project-name',read('project-name'));L.save('project-entry',read('entry-source'));return advance('ready');}
  if(action==='sample-plan'){L.save('sample-plan',true);return advance('crop');}
  if(action==='upload-next'){const file=document.getElementById('plan-file')?.files?.[0];if(!file&&!done('sample-plan'))return error('Elegí DXF/PDF o usá el archivo ficticio del ejemplo.');if(file&&/\.dwg$/i.test(file.name))return error('DWG directo está en investigación. Elegí DXF/PDF o el ejemplo.');L.save('uploaded-name',file?.name??'TS-1P-ejemplo.dxf');return advance('crop');}
  if(action==='select-zone'){L.save('zone-selected',true);return L.refresh();}
  if(action==='enqueue'){const n=Number(read('multiplier'));if(!done('zone-selected'))return error('Seleccioná la zona del tablero tipo.');if(!Number.isInteger(n)||n<1||n>100)return error('Las repeticiones deben ser un entero entre 1 y 100 para esta demo.');L.save('plan-multiplier',n);L.save('engineering-bom',rows().map(r=>({...r,quantity:['sep','cab'].includes(r.id)?r.quantity:r.qtyPlan*n})));L.save('queue-finished',false);return advance('queue');}
  if(action==='queue-complete'){L.save('queue-finished',true);return advance('ready');}
  if(action==='import-bom'){L.save('bom-imported',true);return advance('ready');}
  if(action==='save-correction'){if(!read('coil-voltage')||!read('correction-source')||!checked('technical-confirmation'))return error('Elegí la tensión, indicá su fuente y confirmá la revisión técnica.');if(read('coil-voltage')!=='230 V')return error('La base aprobada R03 utiliza 230 V; un valor diferente debe abrir una nueva revisión técnica.');L.save('coil-voltage',read('coil-voltage'));L.save('correction-source',read('correction-source'));L.save('essentials-complete',read('correction-scope')==='all');return advance('approved');}
  if(action==='review-blocker'){location.href=L.href('d-review.html',{stage:'correct',variant:ctx.variant});return;}
  if(action==='bom-ready'){if(!done('essentials-complete'))return error('El contactor todavía necesita tensión de bobina; conservá el faltante visible.');L.save('bom-saved',true);return advance('ready');}
  if(action==='save-bom'){const inputs=[...document.querySelectorAll('[data-bom-id]')];if(inputs.some(i=>!Number.isFinite(Number(i.value))||Number(i.value)<0||!Number.isInteger(Number(i.value))))return error('Las unidades deben ser números enteros iguales o mayores a cero.');const edited=rows().map(r=>({...r,quantity:Number(inputs.find(i=>i.dataset.bomId===r.id)?.value??r.quantity)}));L.save('engineering-bom',edited);L.save('bom-saved',true);return advance('consolidated');}
  if(action==='save-brand'){L.save('bom-brand',read('bom-brand'));L.save('engineering-message','Preferencia guardada en esta demo; la restricción del pliego sigue requiriendo revisión.');return L.refresh();}
  if(action==='apply-rule'){if(!read('rule-section')||!checked('rule-confirm'))return error('Confirmá la sección y la aprobación antes de agregar la línea derivada.');L.save('rule-section',read('rule-section'));L.save('rule-applied',true);return advance('consolidated');}
  if(action==='alternative-item'){if(!read('alternative-brand-input')||!read('alternative-spec'))return error('Completá marca y especificación de la alternativa o eliminá la opción.');L.save('bom-alternative',{rowId:'ct',brand:read('alternative-brand-input'),specification:read('alternative-spec'),sku:'MB-CT325',approved:false});L.save('alternative-approved',false);L.toast('Alternativa guardada; la base conserva sus datos.');return L.refresh();}
  if(action==='alternative-remove'){L.save('bom-alternative',{rowId:'ct',brand:'',specification:'',sku:'',approved:false});L.save('alternative-approved',false);L.toast('Alternativa eliminada; los seis ítems base siguen disponibles.');return L.refresh();}
  if(action==='alternative-define'){if(!read('alternative-name'))return error('Nombrá el escenario para conservar su motivo.');L.save('alternative-name',read('alternative-name'));L.save('alternative-reason',read('alternative-reason'));return advance('compare');}
  if(action==='approve-alternative'){if(!done('essentials-complete'))return error('Primero completá la tensión de bobina con una fuente confirmada.');if(!checked('alternative-tech')||!checked('alternative-brand')||!read('alternative-source'))return error('Confirmá equivalencia técnica, marca admitida y fuente de aprobación.');if(!alternative().brand||!alternative().specification)return error('La alternativa es opcional, pero debe estar definida para aprobar este escenario.');L.save('bom-alternative',{...alternative(),approved:true});L.save('alternative-approved',true);L.save('alternative-source',read('alternative-source'));return advance('trace');}
  if(action==='revision-resolve'){if(!checked('revision-confirm')||!read('revision-reason'))return error('Indicá el motivo y confirmá la autorización del cambio.');L.save('revision-choice',read('revision-choice'));L.save('revision-reason',read('revision-reason'));return advance('impact');}
  if(action==='revision-approve'){L.save('revision-approved',true);return advance('approved');}
  if(definitions[workflow].steps.some(([id])=>id===action))return advance(action);
 }
 const def=definitions[workflow];
 L.boot({title:def.title,subtitle:def.subtitle,role:'engineer',active:'projects',status:def.status,variants:[{id:'guided',label:'Recorrido guiado',description:'Decisiones secuenciales, fuente visible y una acción siguiente. Recomendado para un primer proyecto.'},{id:'expert',label:'Espacio experto',description:'Acceso directo y comparación de plano/lista. Misma información inicial; recomendado para revisión repetitiva y BOM propio.'}],steps:def.steps.map(([id,label])=>({id,label})),render:ctx=>`${workflow==='review'||(workflow==='bom'&&!done('essentials-complete'))?note('Fase de revisión del dato de origen','La cotización base R03 utiliza 3P · 25 A · bobina 230 V del catálogo. Este recorrido ensaya la revisión previa de una detección cuyo dato de bobina todavía debe confirmarse; aprobarlo reconcilia el origen con esa base. No cambia una oferta ya enviada.') : ''}${renderers[workflow](ctx)}`,onAction,afterRender(){const input=document.getElementById('plan-file');if(input)input.addEventListener('change',()=>{document.getElementById('plan-file-name').textContent=input.files?.[0]?.name??'Ningún archivo seleccionado';});}});
})();
