(() => {
  'use strict';
  const L = window.L;
  const B = window.B;
  const file = location.pathname.split('/').pop();
  const esc = L.escape;
  const rows = B.bom;
  const rowById = id => rows.find(row => row.id === id) || rows[0];
  const saved = (key, fallback) => L.get(`lifecycle-${key}`, fallback);
  const put = (key, value) => L.save(`lifecycle-${key}`, value);
  const btn = (label, action, kind = 'secondary', extra = '') => `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
  const link = (label, target, params = {}, kind = 'secondary') => `<a class="btn ${kind}" href="${L.href(target, params)}">${label}</a>`;
  const card = (title, content, sub = '') => `<section class="card"><div class="card-head"><div><h2>${title}</h2>${sub ? `<p class="muted small">${sub}</p>` : ''}</div></div><div class="card-body">${content}</div></section>`;
  const note = (title, text, tone = 'blue') => L.note(title, text, tone);
  const field = (label, name, value, type = 'text', more = '') => `<label class="field"><span>${label}</span><input id="${name}" name="${name}" type="${type}" value="${esc(String(value))}" ${more}></label>`;
  const input = name => document.getElementById(name)?.value?.trim() || '';
  const feedback = () => saved('feedback', '') ? note('Actualización de la demo', esc(saved('feedback', ''))) : '';
  const inform = message => { put('feedback', message); L.refresh(); };
  const bomTable = (action = null) => `<div class="life-bom-table">${L.table(['Material · referencia', 'Especificación', 'Cantidad a comprar', 'Origen'], rows.map(row => [
    `${action ? btn(esc(row.material), `${action}:${row.id}`, 'ghost') : `<strong>${esc(row.material)}</strong>`}<div class="small muted mono">${esc(row.sku)}</div>`, esc(row.specification), `${L.num(row.quantity)} ${esc(row.unit)}`, esc(row.source)
  ]))}</div>`;
  const documentList = docs => `<div>${docs.map(([name, revision, action]) => `<div class="life-doc">${L.icon('file')}<div><strong>${name}</strong><div class="small muted">${revision}</div></div>${btn('Ver documento', `doc:${action}`, 'ghost')}</div>`).join('')}</div>`;
  const receipt = () => saved('receipt', {});
  const isComplete = () => rows.every(row => receipt()[row.id] === true);
  const released = () => saved('release', false);
  const operations = () => saved('operations', []);
  const checks = () => saved('checks', {});
  const qualityReady = () => ['continuity', 'labels', 'functional'].every(key => checks()[key]);
  const completeDossier = () => saved('dossier', false);
  const materialDescription = row => `${row.material} · ${row.specification}`;
  const stageLink = (label, stage, kind = 'secondary') => btn(label, `stage:${stage}`, kind);

  function panelScene(ctx) {
    const selected = saved('panel-selected', 'tm');
    const angle = saved('panel-angle', 28);
    const exploded = saved('panel-exploded', false);
    const mode = saved(`panel-mode-${ctx.variant}`, ctx.variant === 'table' ? 'table' : '3d');
    const positions = [{ x: 95, y: 95, w: 150, h: 85 }, { x: 260, y: 95, w: 125, h: 85 }, { x: 100, y: 225, w: 110, h: 85 }, { x: 270, y: 225, w: 120, h: 85 }, { x: 100, y: 340, w: 215, h: 58 }, { x: 325, y: 360, w: 85, h: 38 }];
    const cube = (styles, face, attrs = '') => `<button class="panel-cube" style="${styles}" ${attrs}>${['front', 'back', 'left', 'right', 'top', 'bottom'].map(side => `<span class="panel-face ${side}">${side === 'front' ? face : ''}</span>`).join('')}</button>`;
    const geometry = `<div class="panel-viewport ${mode === '2d' ? 'flat' : ''}" id="panel-viewport" tabindex="0" role="group" aria-label="Representación conceptual del tablero. Flechas izquierda y derecha giran; Tab recorre los seis grupos de materiales; Enter selecciona."><div class="panel-scene" style="--angle:${angle}deg">${cube('--w:430px;--h:455px;--d:18px;--x:35px;--y:10px;--z:-20px', '<span class="panel-part-title">Gabinete · 1 u · dimensiones orientativas</span>', `data-action="select:cab" aria-pressed="${selected === 'cab'}" aria-label="Seleccionar gabinete, una unidad en el BOM"`)}${rows.map((row, index) => { if (row.id === 'cab') return ''; const p = positions[index]; return cube(`--w:${p.w}px;--h:${p.h}px;--d:${index < 4 ? 38 : 20}px;--x:${p.x}px;--y:${p.y}px;--z:${exploded ? 95 + index * 20 : 16}px`, `<span class="panel-part-title">${esc(row.material)}</span>${index < 4 ? '<span class="panel-switch"></span>' : '<span class="panel-contacts"><i></i><i></i><i></i><i></i></span>'}<span class="panel-part-title mono">${L.num(row.quantity)} ${esc(row.unit)}</span>`, `data-action="select:${row.id}" aria-pressed="${selected === row.id}" aria-label="Seleccionar ${esc(materialDescription(row))}, ${row.quantity} ${esc(row.unit)} en BOM"`); }).join('')}</div><div class="panel-annotation">Agrupación conceptual de seis materiales · proporciones y posiciones orientativas</div></div>`;
    const row = rowById(selected);
    return `<div class="panel-layout">${card(mode === 'table' ? 'Los mismos materiales, en tabla' : 'TS-1P · ensamble conceptual', `${mode === 'table' ? bomTable('select') : geometry}<div class="toolbar">${btn('3D', 'mode:3d', mode === '3d' ? 'primary' : 'secondary')}${btn('2D', 'mode:2d', mode === '2d' ? 'primary' : 'secondary')}${btn('Tabla accesible', 'mode:table', mode === 'table' ? 'primary' : 'secondary')}</div>${mode !== 'table' ? `<div class="toolbar">${btn('Girar −15°', 'rotate:left')}${btn('Girar +15°', 'rotate:right')}${btn(exploded ? 'Volver a ensamblar' : 'Separar las piezas', 'explode')}${btn('Restablecer vista', 'reset-view')}</div><p class="small muted">Usá las flechas ← / → en el visor para girar y Tab para recorrer los grupos. La tabla ofrece la misma selección y cantidades.</p>` : ''}`, 'Selección compartida entre 3D, 2D y tabla')}${card('Material seleccionado', `<div aria-live="polite"><p class="small muted">BOM · ${esc(B.project.revision)}</p><h3>${esc(row.material)}</h3><p>${esc(row.specification)}</p><div class="life-bom-ref"><strong>${L.num(row.quantity)} ${esc(row.unit)} a comprar</strong><div class="small muted">${esc(row.source)} · código ${esc(row.sku)}</div></div><p class="small">La figura reúne unidades equivalentes en un grupo. No representa la implantación de las ${row.quantity} unidades ni dimensiones de fabricación.</p></div><div class="stack">${link('Abrir fila en BOM', 'd-bom.html', { stage: 'edit', row: row.id, variant: 'expert' })}${stageLink('Revisar correspondencia', 'review', 'primary')}</div>`)} </div>`;
  }

  function panel(ctx) {
    if (ctx.stage === 'review') {
      return feedback() + card('Correspondencia antes de fabricar', `${note('Modelo conceptual · validar con ingeniería', 'Ni el emplazamiento ni la geometría sustituyen un plano aprobado, cálculo eléctrico o verificación reglamentaria. Los seis grupos corresponden al mismo BOM de ejemplo.')}${bomTable('select')}<label class="life-check"><input id="panel-reviewed" type="checkbox" ${saved('panel-reviewed', false) ? 'checked' : ''}><span>Revisé la correspondencia entre el concepto y la lista de materiales R03. Esto no aprueba un diseño eléctrico.</span></label><div class="footer-actions">${stageLink('Volver al modelo', 'model')}${btn('Registrar revisión conceptual', 'panel-approve', 'primary')}</div>`);
    }
    if (ctx.stage === 'handoff') return feedback() + card('Concepto entregado a preparación de taller', `${note(saved('panel-reviewed', false) ? 'Revisión conceptual registrada' : 'Revisión conceptual pendiente', saved('panel-reviewed', false) ? 'El BOM R03 queda referenciado en el pedido de preparación. Taller tendrá que verificar materiales y recibir la versión formal de ingeniería.' : 'Registrá primero la revisión. Navegar a esta etapa no libera fabricación.', saved('panel-reviewed', false) ? 'green' : 'amber')}<div class="life-status-strip"><div class="metric"><small>Tablero</small><strong>${esc(B.project.board)}</strong></div><div class="metric"><small>Versión BOM</small><strong>${esc(B.project.revision)}</strong></div><div class="metric"><small>Materiales</small><strong>6 grupos</strong></div><div class="metric"><small>Revisión</small><strong>${saved('panel-reviewed', false) ? 'Registrada' : 'Pendiente'}</strong></div></div><div class="footer-actions">${stageLink('Revisar correspondencia', 'review')}${link('Preparar fabricación', 'd-workshop.html', { stage: 'readiness', variant: 'guided' }, 'primary')}</div>`);
    return note('Nuevo · concepto de tablero', 'Representación geométrica propia, vinculada al BOM. La implantación, dimensiones y agrupaciones son hipótesis de UX; no es un gemelo digital ni un diseño certificado.') + panelScene(ctx);
  }

  function workshop(ctx) {
    const count = rows.filter(row => receipt()[row.id]).length;
    if (ctx.variant === 'board' && ctx.stage === 'readiness') return feedback() + card('Control de la orden · cuatro frentes de trabajo', `<div class="grid equal">${[['Materiales', `${count}/6 filas recibidas`, 'readiness', 'Recepción individual o completa, sin consumo automático.'], ['Versión', released() ? 'R03 liberada' : 'Por liberar', 'release', 'Referencia formal de ingeniería y BOM congelados.'], ['Operaciones', `${operations().length} registros`, 'operation', 'Horas y cantidades efectivamente consumidas.'], ['Legajo', completeDossier() ? 'Consolidado' : 'Pendiente', 'quality', 'Controles internos y documentos, sin certificación.']].map(([title, status, step, desc]) => `<div class="card"><div class="card-body"><p class="small muted">${title}</p><h3>${status}</h3><p class="small">${desc}</p>${step === 'readiness' ? btn('Abrir recepción guiada', 'variant:guided', 'primary') : stageLink('Abrir registro', step)}</div></div>`).join('')}</div>${note('Mismas condiciones de liberación', 'Esta vista resume los frentes de una orden. Abrir una etapa no saltea sus comprobaciones ni libera trabajo.')}`);
    if (ctx.stage === 'readiness') return feedback() + `<div class="grid two">${card('Disponibilidad de materiales', `<div class="spread"><strong>${count} de ${rows.length} filas completas</strong>${L.badge(isComplete() ? 'Listo para revisar versión' : 'Pendientes de recepción', isComplete() ? 'green' : 'amber')}</div><div class="life-progress" style="margin:14px 0"><i style="width:${count / rows.length * 100}%"></i></div>${L.table(['Material', 'Necesidad', 'Recepción de ejemplo'], rows.map(row => [`<strong>${esc(row.material)}</strong><div class="small muted">${esc(row.sku)}</div>`, `${L.num(row.quantity)} ${esc(row.unit)}`, btn(receipt()[row.id] ? 'Recibido · desmarcar' : 'Registrar recepción completa', `receive:${row.id}`, receipt()[row.id] ? 'ghost' : 'secondary', `aria-pressed="${Boolean(receipt()[row.id])}"`)]))}<div class="footer-actions">${btn('Simular recepción de las seis filas', 'receive-all')}${stageLink('Revisar versión y liberar', 'release', 'primary')}</div>`)}${card('Orden de fabricación · OF-026-014', `<p>${esc(B.project.name)}</p><div class="life-revision"><strong>${esc(B.project.board)}</strong>${L.badge(B.project.revision)}<span class="small muted">El BOM de compra gobierna la necesidad.</span></div>${note('Puerta de preparación propuesta', 'La liberación requiere materiales completos y una versión formal revisada. Si hay faltantes, la orden queda en preparación; no se descuenta consumo por recibir.')}${link('Revisar BOM', 'd-bom.html', { variant: 'expert' })}${link('Ver concepto de tablero', 'd-panel.html', { stage: 'model' })}`)}</div>`;
    if (ctx.stage === 'release') return feedback() + card('Liberar una versión para taller', `${note(isComplete() ? 'Materiales completos' : 'Hay materiales pendientes', isComplete() ? 'La recepción de todas las filas está registrada en la demo.' : 'Volvé a preparación para registrar lo recibido. El botón de liberación no permite avanzar con faltantes.', isComplete() ? 'green' : 'amber')}${L.table(['Documento', 'Versión congelada', 'Estado propuesto'], [['BOM de fabricación', B.project.revision, L.badge('Referencia de demo')], ['Plano de ingeniería', 'R03 · ejemplo', L.badge('Revisión humana requerida', 'amber')], ['Concepto geométrico', 'V1', L.badge('Orientativo', 'gray')]])}<label class="life-check"><input id="release-reviewed" type="checkbox" ${released() ? 'checked' : ''}><span>Simular que ingeniería aprobó la versión formal R03 para esta orden. No acredita una aprobación real.</span></label><label class="field"><span>Responsable de liberación</span><input id="release-owner" value="Elena Ruiz · ejemplo" readonly></label><div class="footer-actions">${stageLink('Volver a preparación', 'readiness')}${btn(released() ? 'Versión ya liberada · ir a operaciones' : 'Simular liberación R03', 'release-order', 'primary', !isComplete() ? 'disabled' : '')}</div>`);
    if (ctx.stage === 'operation') {
      const consumed = saved('consumed', {});
      const hours = operations().reduce((sum, op) => sum + op.hours, 0);
      return feedback() + card('Registrar trabajo y consumo real', `${note(released() ? 'Orden liberada · R03' : 'Orden pendiente de liberación', released() ? 'Cada registro queda asociado a R03. Los materiales recibidos y los consumidos se registran por separado.' : 'Primero completá recepción y registrá la versión aprobada. Podés revisar esta pantalla, pero no registrar operaciones.', released() ? 'green' : 'amber')}<div class="grid equal"><div class="stack"><label class="field"><span>Operación</span><select id="operation-name"><option>Armado mecánico</option><option>Cableado</option><option>Identificación</option></select></label>${field('Horas trabajadas en esta operación', 'operation-hours', 2, 'number', 'min="0.25" max="100" step="0.25"')}${btn('Registrar operación', 'add-operation', 'primary', !released() ? 'disabled' : '')}</div><div><div class="metric"><small>Horas registradas</small><strong>${L.num(hours)} h</strong></div>${operations().length ? `<div class="timeline">${operations().map(op => `<div class="list-item"><strong>${esc(op.name)}</strong><span>${L.num(op.hours)} h · R03</span></div>`).join('')}</div>` : note('Sin operaciones', 'Al registrar horas, se actualizará el avance de esta orden de ejemplo.', 'gray')}</div></div><div class="divider"></div>${L.table(['Material', 'Previsto', 'Consumido acumulado', 'Registrar'], rows.map(row => [`${esc(row.material)}`, `${L.num(row.quantity)} ${esc(row.unit)}`, `<label><span class="life-sr">Consumo acumulado de ${esc(row.material)}</span><input class="life-input" id="consume-${row.id}" type="number" min="0" max="${row.quantity * 2}" step="0.1" value="${consumed[row.id] || 0}"></label>`, btn('Guardar consumo', `consume:${row.id}`, 'secondary', !released() ? 'disabled' : '')]))}<div class="footer-actions">${stageLink('Ver liberación', 'release')}${stageLink('Preparar control y legajo', 'quality', 'primary')}</div>`);
    }
    return feedback() + `<div class="grid two">${card('Control y legajo de fabricación', `${note('Lista propuesta, sin certificación', 'Los controles requieren procedimientos, valores y responsables definidos por ingeniería. Las marcas de esta demo no prueban seguridad ni conformidad reglamentaria.', 'amber')}<div class="checklist">${[['continuity', 'Continuidad y conexiones', 'Registro de mediciones según procedimiento interno.'], ['labels', 'Identificación y correspondencia', 'Etiquetas, código de tablero y versión del plano.'], ['functional', 'Revisión funcional', 'Evidencia del control definido por ingeniería.']].map(([key, label, detail]) => `<div class="life-check"><input type="checkbox" id="qa-${key}" ${checks()[key] ? 'checked' : ''} aria-label="${label}"><div><strong>${label}</strong><div class="small muted">${detail}</div></div></div>`).join('')}</div>${btn('Guardar controles de ejemplo', 'save-checks')}<div class="footer-actions">${stageLink('Volver a operaciones', 'operation')}${btn('Consolidar legajo de ejemplo', 'finish-dossier', 'primary')}</div>`)}${card('Documentos para entrega', `${documentList([['BOM y consumo', 'R03 · cantidades previstas / consumidas', 'bom'], ['Registro de operaciones', `${operations().length} registros · ejemplo`, 'operations'], ['Lista de controles', 'Procedimiento a definir · sin certificado', 'quality']])}${completeDossier() ? note('Legajo de ejemplo consolidado', 'Disponible para recepción en obra y registro del activo.', 'green') : note('Legajo pendiente', 'Se requiere orden liberada, al menos una operación y tres controles registrados.', 'amber')}<div class="stack">${link('Abrir recepción en obra', 'm-field.html', { stage: 'receipt', variant: 'checklist' })}${link('Abrir registro del activo', 'd-asset.html', { stage: 'record', variant: 'dossier' })}</div>`)} </div>`;
  }

  function fieldPage(ctx) {
    const field = saved('field', { received: false, photo: false, change: '', approval: 'none', synced: false });
    if (ctx.variant === 'offline' && ctx.stage === 'receipt') return `<div class="field-page">${feedback()}${card('Bandeja local de obra', `${note('Trabajo sin conexión · propuesta', 'Los registros quedan en este navegador. La sincronización productiva y los permisos de aprobación requieren implementación.', 'amber')}<div class="timeline"><div class="list-item"><strong>Recepción TS-1P</strong>${L.badge(field.received ? 'Guardada localmente' : 'Por registrar', 'gray')}</div><div class="list-item"><strong>Diferencia CH-014</strong>${L.badge(field.approval === 'none' ? 'Sin diferencia' : field.approval === 'pending' ? 'En espera de decisión' : 'Decisión de ejemplo guardada', 'gray')}</div><div class="list-item"><strong>Envío al legajo</strong>${L.badge(field.synced ? 'Simulado' : 'Pendiente', 'amber')}</div></div><div class="stack">${btn('Abrir lista de recepción', 'variant:checklist', 'primary')}${stageLink('Registrar diferencia local', 'change')}${stageLink('Revisar antes de sincronizar', 'sync')}</div>`)} </div>`;
    const summary = `<div class="life-revision"><strong>${esc(B.project.board)}</strong>${L.badge(B.project.revision)}<span class="small">OT-026-014 · ejemplo</span></div>`;
    if (ctx.stage === 'receipt') return `<div class="field-page">${feedback()}${card('Recibir tablero en obra', `${summary}${note(completeDossier() ? 'Legajo de fabricación listo en la demo' : 'Legajo de fabricación pendiente', completeDossier() ? 'Contrastá el envío con la orden y sus documentos antes del montaje.' : 'La recepción puede registrarse con una reserva. La liberación de instalación requiere completar el legajo en taller.', completeDossier() ? 'green' : 'amber')}<div class="life-mini-plan"><div class="life-board"><i></i><i></i><i></i><i></i></div><div><strong>TS-1P</strong><p class="small muted">Identificación de bulto<br>Imagen esquemática</p></div></div><label class="life-check"><input id="receipt-id" type="checkbox" ${field.received ? 'checked' : ''}><span>Identificación del tablero coincide con la orden.</span></label><label class="life-check"><input id="receipt-condition" type="checkbox" ${field.received ? 'checked' : ''}><span>Embalaje y estado exterior revisados.</span></label>${btn('Registrar recepción de ejemplo', 'field-receive', 'primary')}<div class="footer-actions">${stageLink('Registrar faltante o cambio', 'change')}${stageLink('Ver sincronización', 'sync')}</div>`)} </div>`;
    if (ctx.stage === 'change') return `<div class="field-page">${feedback()}${card('Registrar una diferencia en obra', `${summary}<label class="field"><span>Tipo de diferencia</span><select id="field-change-type"><option>Faltante de material</option><option>Cambio de montaje</option><option>Daño en entrega</option></select></label><label class="field"><span>Material afectado</span><select id="field-material">${rows.map(row => `<option value="${row.id}" ${field.material === row.id ? 'selected' : ''}>${esc(row.material)}</option>`).join('')}</select></label>${fieldControl('Cantidad afectada', 'field-change-qty', field.qty || 2, 'number', 'min="1" max="100"') }<label class="field"><span>Descripción</span><textarea id="field-change-text" rows="3" placeholder="Describí qué falta o qué cambió.">${esc(field.change || '')}</textarea></label><div class="field-photo">${field.photo ? '<div><strong>Evidencia de ejemplo adjunta</strong><p class="small muted">Esquema local · no se capturó una fotografía</p><div class="life-board" style="margin:12px auto"><i></i><i></i><i></i></div></div>' : '<div><strong>Sin evidencia adjunta</strong><p class="small muted">Podés simular un adjunto para revisar el flujo.</p></div>'}</div>${btn(field.photo ? 'Quitar evidencia simulada' : 'Adjuntar evidencia simulada', 'field-photo')}<div class="footer-actions">${stageLink('Volver a recepción', 'receipt')}${btn('Guardar cambio y pedir aprobación', 'field-request', 'primary')}</div>`)} </div>`;
    if (ctx.stage === 'approval') return `<div class="field-page">${feedback()}${card('Esperar decisión de ingeniería', `${summary}${field.approval === 'none' ? note('Todavía no hay un cambio enviado', 'Registrá una diferencia antes de solicitar aprobación.', 'amber') : `<div class="life-bom-ref"><strong>${esc(field.type || 'Diferencia')}</strong><p>${esc(field.change)}</p><p class="small muted">${esc(materialDescription(rowById(field.material)))} · ${field.qty || 2} unidades · CH-014</p></div>${L.badge(field.approval === 'pending' ? 'Pendiente de aprobación' : field.approval === 'approved' ? 'Aprobado en simulación' : 'Rechazado en simulación', field.approval === 'approved' ? 'green' : 'amber')}`}${note('Decisión simulada de otro rol', 'Estos botones permiten revisar la respuesta en el prototipo. En el producto, autorizaría un responsable con permisos definidos, no la persona que reporta el cambio.', 'gray')}<div class="stack">${btn('Simular aprobación de ingeniería', 'field-approve', 'primary', field.approval === 'none' ? 'disabled' : '')}${btn('Simular rechazo · conservar versión', 'field-reject', 'secondary', field.approval === 'none' ? 'disabled' : '')}${stageLink('Ver impacto económico', 'impact')}${stageLink('Preparar sincronización', 'sync')}</div>`)} </div>`;
    if (ctx.stage === 'impact') return `<div class="field-page">${feedback()}${card('Impacto antes de ejecutar', `${field.approval === 'none' ? note('Sin diferencia registrada', 'Registrá una diferencia en obra para calcular su impacto.', 'amber') : `<p>${esc(field.change)}</p><div class="metric"><small>Material afectado · ejemplo</small><strong>${L.money(rowById(field.material).price * (field.qty || 2))}</strong></div><p class="small muted">Precio de referencia del BOM del 30/09. Mano de obra, impuestos y flete deben completarse. El impacto no modifica la cotización original.</p>`}${link('Abrir control de cambios', 'd-revisions.html', { stage: 'impact', variant: 'guided' })}${stageLink('Volver a decisión', 'approval')}`)} </div>`;
    return `<div class="field-page">${feedback()}${card('Sincronizar y cerrar versión de obra', `${summary}${note(field.synced ? 'Registro sincronizado en la demo' : ctx.state === 'sin-conexion' ? 'Registro guardado localmente' : 'Cambios preparados para sincronizar', field.synced ? 'Recepción y decisiones quedan en el legajo de ejemplo. Se mantiene el historial anterior.' : 'La simulación guarda recepción, diferencia y decisión en este navegador. No existe un envío real al servidor.', field.synced ? 'green' : 'blue')}<div class="timeline"><div class="list-item"><strong>Recepción</strong>${L.badge(field.received ? 'Registrada' : 'Pendiente', field.received ? 'green' : 'amber')}</div><div class="list-item"><strong>Diferencia CH-014</strong>${L.badge(field.approval === 'approved' ? 'Aprobada' : field.approval === 'rejected' ? 'Rechazada' : field.approval === 'pending' ? 'Pendiente' : 'Sin cambios', field.approval === 'approved' ? 'green' : 'gray')}</div><div class="list-item"><strong>Documentación conforme a obra</strong>${L.badge(field.synced ? `${field.approval === 'approved' ? 'R04' : 'R03'} · ejemplo` : 'Sin consolidar', 'gray')}</div></div><div class="stack">${btn('Simular sincronización', 'field-sync', 'primary')}${link('Abrir legajo del activo', 'd-asset.html', { stage: 'documents', variant: 'dossier' })}${stageLink('Volver a recepción', 'receipt')}</div>`)} </div>`;
  }
  const fieldControl = field;

  function asset(ctx) {
    const site = saved('field', { synced: false });
    const siteRevision = site.synced && site.approval === 'approved' ? 'R04' : 'R03';
    if (ctx.variant === 'service' && ctx.stage === 'record') return feedback() + `<div class="grid equal">${card('Partir de un repuesto instalado', `<p>Seleccioná una fila del BOM R03 para conservar su identidad en la solicitud.</p>${bomTable('spare')}${stageLink('Consultar solicitud y ofertas', 'spares', 'primary')}`)}${card('Coordinar una intervención', `<p>Reuní los documentos vigentes y definí quién coordina la visita. No se prescribe un trabajo técnico desde esta pantalla.</p>${note('Versión de referencia', site.synced ? `${siteRevision} de obra disponible en la demo.` : 'R03 de taller; documentación de obra pendiente.', 'gray')}<div class="stack">${stageLink('Crear pedido de servicio', 'service', 'primary')}${stageLink('Consultar legajo', 'documents')}</div>`)}</div>`;
    if (ctx.stage === 'record') return feedback() + `<div class="grid two">${card('Activo · TS-1P', `<div class="life-mini-plan"><div class="life-board"><i></i><i></i><i></i><i></i></div><div><h3>${esc(B.project.board)}</h3><p class="muted">Centro Aurora · planta 1</p><p class="small mono">ACT-AUR-TS1P · ejemplo</p></div></div><div class="life-status-strip" style="margin-top:18px"><div class="metric"><small>Versión</small><strong>${site.synced ? `${siteRevision} obra` : 'R03 taller'}</strong></div><div class="metric"><small>Legajo</small><strong>${completeDossier() ? 'Consolidado' : 'Pendiente'}</strong></div><div class="metric"><small>Entrega</small><strong>${site.received ? 'Recibida' : 'Por registrar'}</strong></div><div class="metric"><small>Materiales</small><strong>6 grupos</strong></div></div><div class="footer-actions">${stageLink('Ver documentos y trazabilidad', 'documents', 'primary')}${stageLink('Consultar repuestos', 'spares')}</div>`)}${card('Responsable de la instalación', `<p><strong>Elena Ruiz · ejemplo</strong></p><p class="muted small">Azul Ingeniería</p><p class="small">El activo propuesto conserva la relación entre el BOM aprobado, la fabricación y los cambios en obra.</p>${note('Propuesta de continuidad del producto', 'No hay registro de activos ni mantenimiento integrado en dev. Los permisos, retención documental y responsables deben validarse con el cliente.')}${link('Volver al proyecto', 'd-projects.html')}`)}</div>`;
    if (ctx.stage === 'documents') return feedback() + `<div class="grid two">${card('Legajo documental', `${documentList([['BOM de materiales', 'R03 · base compartida', 'bom'], ['Registro de fabricación', completeDossier() ? 'Consolidado · demo' : 'Pendiente de taller', 'operations'], ['Controles internos', 'Lista de ejemplo · sin certificado', 'quality'], ['Registro de recepción', site.received ? 'Recibido · demo' : 'Pendiente', 'receipt'], ['Plano conforme a obra', site.synced ? `${siteRevision} · cierre de ejemplo` : 'Pendiente de cierre en obra', 'asbuilt']])}<div class="footer-actions">${btn('Descargar legajo de ejemplo', 'download-dossier', 'primary')}${stageLink('Preparar mantenimiento', 'service')}</div>`)}${card('Historia de versiones', `<div class="timeline"><div class="list-item"><strong>R03 · BOM</strong><span class="small muted">Lista compartida con cotización</span></div><div class="list-item"><strong>R03 · taller</strong><span class="small muted">${released() ? 'Liberada en demo' : 'Pendiente liberación'}</span></div><div class="list-item"><strong>R04 · obra</strong><span class="small muted">${site.synced ? 'Recepción y decisiones de demo' : 'Pendiente sincronización'}</span></div></div>${link('Revisar cambios', 'd-revisions.html', { stage: 'diff', variant: 'expert' })}${link('Abrir recepción en obra', 'm-field.html', { stage: 'sync', variant: 'checklist' })}`)}</div>`;
    if (ctx.stage === 'spares') {
      const requested = saved('spare-request', null);
      return feedback() + card('Repuesto desde el material instalado', `${note('Identidad del material, sin sustitución automática', 'La solicitud conserva el material y los atributos del BOM. Un sustituto requiere revisión técnica; la demo no confirma disponibilidad ni equivalencia segura.')}${L.table(['Material instalado', 'Especificación / código', 'Repuesto'], rows.map(row => [esc(row.material), `${esc(row.specification)}<div class="small muted mono">${esc(row.sku)}</div>`, btn('Solicitar 1 unidad', `spare:${row.id}`)]))}${requested ? `<div class="life-bom-ref"><strong>Solicitud de ejemplo REP-014</strong><p>${esc(materialDescription(rowById(requested)))} · 1 ${esc(rowById(requested).unit)}</p><p class="small muted">Referencia ${esc(rowById(requested).sku)} · pendiente de cotización</p>${link('Comparar ofertas de referencia', 'd-quote.html', { stage: 'offers', variant: 'guided' })}</div>` : ''}<div class="footer-actions">${stageLink('Volver al registro', 'record')}${stageLink('Preparar orden de servicio', 'service', 'primary')}</div>`);
    }
    const maintenance = saved('maintenance', null);
    return feedback() + card('Entregar documentación para servicio', `${note('Plan de mantenimiento a definir', 'Las tareas, periodicidad y cualificación del responsable se validan con ingeniería y fabricante. Este flujo documenta un pedido; no prescribe trabajos eléctricos.')}${field('Fecha propuesta para revisión documental', 'service-date', '2026-11-20', 'date')}${field('Responsable de coordinación', 'service-owner', 'Elena Ruiz · ejemplo')}<label class="field"><span>Motivo del servicio</span><textarea id="service-reason" rows="3">Revisar el legajo y coordinar un relevamiento según el procedimiento del cliente.</textarea></label><div class="footer-actions">${stageLink('Volver al legajo', 'documents')}${btn('Crear pedido de servicio de ejemplo', 'service-create', 'primary')}</div>${maintenance ? `<div class="life-bom-ref"><strong>SER-014 · coordinación pendiente</strong><p>${esc(maintenance.reason)}</p><p class="small muted">${esc(maintenance.date)} · ${esc(maintenance.owner)} · legajo ${siteRevision}</p></div>` : ''}`);
  }

  const configs = {
    'd-panel.html': { title: 'Del BOM al concepto de tablero', subtitle: 'Seis grupos de materiales, una selección compartida.', active: 'projects', variants: [{ id: 'model', label: 'Modelo interactivo', description: 'Selección espacial con correspondencia al BOM; revisar y entregar a taller.' }, { id: 'table', label: 'Revisión en tabla', description: 'Mismos datos y decisiones mediante una lista accesible, sin representación espacial.' }], steps: [{ id: 'model', label: 'Concepto' }, { id: 'review', label: 'Correspondencia' }, { id: 'handoff', label: 'Entrega a taller' }], render: panel },
    'd-workshop.html': { title: 'Preparación y fabricación', subtitle: 'OF-026-014 · versión y registros de ejemplo.', active: 'workshop', variants: [{ id: 'guided', label: 'Preparación guiada', description: 'Materiales → versión → operaciones → legajo. Cada puerta registra una decisión explícita.' }, { id: 'board', label: 'Control de orden', description: 'Revisar etapas de una orden y completar sus registros. La liberación conserva las mismas condiciones.' }], steps: [{ id: 'readiness', label: 'Materiales' }, { id: 'release', label: 'Liberación' }, { id: 'operation', label: 'Trabajo y consumo' }, { id: 'quality', label: 'Control y legajo' }], render: workshop },
    'm-field.html': { title: 'Recepción en obra', subtitle: 'TS-1P · centro Aurora · datos de ejemplo.', active: 'projects', variants: [{ id: 'checklist', label: 'Lista de recepción', description: 'Identificar, registrar diferencias y cerrar documentación desde el sitio.' }, { id: 'offline', label: 'Trabajo sin conexión', description: 'Guardar localmente y revisar el estado antes de simular sincronización. No hay servidor real.' }], steps: [{ id: 'receipt', label: 'Recibir' }, { id: 'change', label: 'Diferencia' }, { id: 'approval', label: 'Decisión' }, { id: 'impact', label: 'Impacto' }, { id: 'sync', label: 'Sincronizar' }], render: fieldPage },
    'd-asset.html': { title: 'Legajo y continuidad del activo', subtitle: 'BOM, taller y obra reunidos para consulta y coordinación.', active: 'projects', variants: [{ id: 'dossier', label: 'Legajo documental', description: 'Historial y documentos desde el activo instalado.' }, { id: 'service', label: 'Repuestos y servicio', description: 'Partir del material instalado para solicitar un repuesto o coordinar mantenimiento.' }], steps: [{ id: 'record', label: 'Activo' }, { id: 'documents', label: 'Documentos' }, { id: 'spares', label: 'Repuestos' }, { id: 'service', label: 'Servicio' }], render: asset }
  };

  function download(name, content) {
    const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }));
    const anchor = document.createElement('a');
    anchor.href = url; anchor.download = name; anchor.click();
    URL.revokeObjectURL(url);
  }

  function action(value, element, ctx) {
    const [name, arg] = value.split(':');
    if (name === 'variant') { L.go({ variant: arg }); return; }
    if (name === 'stage') { put('feedback', ''); L.go({ stage: arg }); return; }
    if (name === 'select') { put('panel-selected', arg); L.refresh(); return; }
    if (name === 'mode') { put(`panel-mode-${ctx.variant}`, arg); L.refresh(); return; }
    if (name === 'rotate') { put('panel-angle', saved('panel-angle', 28) + (arg === 'left' ? -15 : 15)); L.refresh(); return; }
    if (name === 'explode') { put('panel-exploded', !saved('panel-exploded', false)); L.refresh(); return; }
    if (name === 'reset-view') { put('panel-angle', 28); put('panel-exploded', false); L.refresh(); return; }
    if (name === 'panel-approve') { if (!document.getElementById('panel-reviewed')?.checked) { inform('Marcá la correspondencia revisada antes de registrar la revisión conceptual.'); return; } put('panel-reviewed', true); L.go({ stage: 'handoff' }); return; }
    if (name === 'receive') { put('receipt', { ...receipt(), [arg]: !receipt()[arg] }); L.refresh(); return; }
    if (name === 'receive-all') { put('receipt', Object.fromEntries(rows.map(row => [row.id, true]))); inform('Las seis filas se marcaron recibidas en la simulación. No se registró un movimiento de inventario real.'); return; }
    if (name === 'release-order') { if (!isComplete() || !document.getElementById('release-reviewed')?.checked) { inform('Requiere recepción completa y confirmación de revisión de ingeniería.'); return; } put('release', true); put('feedback', 'R03 liberada en la simulación. Se conserva esta versión en los registros de taller.'); L.go({ stage: 'operation' }); return; }
    if (name === 'add-operation') { const hours = Number(input('operation-hours')); if (!released() || !(hours > 0 && hours <= 100)) { inform('La orden debe estar liberada y las horas deben ser mayores que cero y como máximo 100.'); return; } put('operations', [...operations(), { name: input('operation-name'), hours }]); inform('Operación registrada en R03. Las horas se acumularon; el consumo se registra por material.'); return; }
    if (name === 'consume') { const quantity = Number(input(`consume-${arg}`)); const row = rowById(arg); if (!released() || !Number.isFinite(quantity) || quantity < 0 || quantity > row.quantity * 2) { inform('Indicá un consumo válido entre cero y dos veces lo previsto, con la orden liberada.'); return; } put('consumed', { ...saved('consumed', {}), [arg]: quantity }); inform(quantity > row.quantity ? 'Consumo superior al previsto registrado como diferencia de ejemplo. Requiere revisión del responsable.' : 'Consumo acumulado guardado para este material.'); return; }
    if (name === 'save-checks') { put('dossier', false); put('checks', Object.fromEntries(['continuity', 'labels', 'functional'].map(key => [key, Boolean(document.getElementById(`qa-${key}`)?.checked)]))); inform('Lista de controles guardada como ejemplo. No es un certificado.'); return; }
    if (name === 'finish-dossier') { if (!released() || !operations().length || !qualityReady()) { inform('Falta una orden liberada, al menos una operación o alguno de los tres controles guardados.'); return; } put('dossier', true); inform('Legajo consolidado de ejemplo. Puede consultarse en obra y en el registro del activo.'); return; }
    if (name.startsWith('field-')) {
      const f = saved('field', { received: false, photo: false, change: '', approval: 'none', synced: false });
      if (name === 'field-receive') { if (!document.getElementById('receipt-id')?.checked || !document.getElementById('receipt-condition')?.checked) { inform('Revisá identificación y estado exterior antes de registrar recepción.'); return; } put('field', { ...f, received: true, synced: false }); inform(completeDossier() ? 'Recepción registrada en este navegador.' : 'Recepción registrada con reserva: legajo pendiente en taller.'); return; }
      if (name === 'field-photo') { put('field', { ...f, photo: !f.photo, change: input('field-change-text') || f.change, material: input('field-material'), qty: Number(input('field-change-qty')) || 2, type: input('field-change-type') }); L.refresh(); return; }
      if (name === 'field-request') { const text = input('field-change-text'); const qty = Number(input('field-change-qty')); if (!text || !Number.isFinite(qty) || qty < 1 || qty > 100) { inform('Completá la diferencia y una cantidad entre 1 y 100.'); return; } put('field', { ...f, type: input('field-change-type'), material: input('field-material'), qty, change: text, approval: 'pending', synced: false }); L.go({ stage: 'approval' }); return; }
      if (name === 'field-approve' || name === 'field-reject') { if (f.approval === 'none') return; put('field', { ...f, approval: name === 'field-approve' ? 'approved' : 'rejected', synced: false }); inform(name === 'field-approve' ? 'Aprobación de ingeniería simulada. La revisión original permanece en el historial.' : 'Rechazo de ingeniería simulado. Se mantiene la versión anterior.'); return; }
      if (name === 'field-sync') { if (ctx.state === 'sin-conexion') { inform('Sin conexión: el registro sigue guardado localmente. Cambiá el estado a normal para simular envío.'); return; } if (!f.received || f.approval === 'pending') { inform('Registrá recepción y resolvé las diferencias pendientes antes de consolidar.'); return; } put('field', { ...f, synced: true }); inform('Sincronización de ejemplo completada en este navegador; no se envió información real.'); return; }
    }
    if (name === 'spare') { put('spare-request', arg); inform('REP-014 creada como solicitud de ejemplo; disponibilidad y equivalencia requieren confirmación.'); return; }
    if (name === 'service-create') { const date = input('service-date'); const owner = input('service-owner'); const reason = input('service-reason'); if (!date || !owner || !reason) { inform('Completá fecha, responsable y motivo del pedido.'); return; } put('maintenance', { date, owner, reason }); inform('Pedido de coordinación SER-014 guardado en la demo. No se notificó a ningún tercero.'); return; }
    if (name === 'doc' || name === 'download-dossier') { const title = name === 'doc' ? arg : 'legajo'; download(`LIARD-${title}-EJEMPLO.txt`, `LIARD · DOCUMENTO DE EJEMPLO\n${B.project.name}\nTablero ${B.project.board} · BOM ${B.project.revision}\nRepresentación de flujo. No es un plano aprobado ni certificado.\n\n${rows.map(row => `${row.material} | ${row.specification} | ${row.quantity} ${row.unit} | ${row.sku}`).join('\n')}\n\nOperaciones: ${JSON.stringify(operations())}\nConsumos: ${JSON.stringify(saved('consumed', {}))}\nControles de ejemplo: ${JSON.stringify(checks())}\nObra: ${JSON.stringify(saved('field', {}))}`); inform('Se descargó un documento de ejemplo con los datos de la demo.'); }
  }

  document.body && (document.body.dataset.lifecycle = file);
  const config = configs[file];
  if (!config) return;
  document.addEventListener('keydown', event => {
    if (!event.target.closest('#panel-viewport') || !['ArrowLeft', 'ArrowRight'].includes(event.key)) return;
    event.preventDefault();
    put('panel-angle', saved('panel-angle', 28) + (event.key === 'ArrowLeft' ? -15 : 15));
    const scene = document.querySelector('.panel-scene');
    if (scene) scene.style.setProperty('--angle', `${saved('panel-angle', 28)}deg`);
  });
  L.boot({ ...config, role: 'engineer', status: 'Propuesta · validar', onAction: action });
})();
