document.addEventListener('DOMContentLoaded',()=>{
  if(document.body.dataset.gallery) return;
  const nav=[['d-projects.html','project','Proyectos','engineer'],['d-engineering.html','plan','Ingeniería','engineer'],['d-panel.html','cube','Tablero 3D','engineer'],['d-rfq.html','send','Solicitudes','engineer'],['d-supplier.html','catalog','Portal proveedor','supplier'],['d-comparison.html','compare','Comparar ofertas','engineer'],['d-orders.html','order','Pedidos','engineer'],['d-operations.html','chart','Costo y margen','engineer'],['d-collaboration.html','users','Equipo y reglas','engineer'],['d-network.html','network','Red y conectores','engineer'],['m-field.html','field','Obra y activos','field']];
  const vNames={guided:'Guiada',expert:'Experta',assisted:'Asistida',visual:'Visual'};
  const p=L.project();
  const role=document.body.dataset.role;
  const visibleNav=role==='supplier'?nav.filter(([file])=>file==='d-supplier.html'):role==='field'?nav.filter(([file])=>['m-field.html','d-panel.html'].includes(file)):nav;
  const page=document.getElementById('page'),act=document.getElementById('act');
  const sidebar=document.createElement('aside');sidebar.className='sidebar';sidebar.setAttribute('aria-label','Navegación principal');sidebar.innerHTML=`<a class="wordmark" href="${L.href('index.html')}"><span class="brand-mark">${L.icon('cube')}</span>liard<span class="badge green">lab</span></a><small>Expediente eléctrico</small><nav>${nav.map(([file,ico,label])=>`<a class="nav-link ${L.page()===file?'active':''}" ${L.page()===file?'aria-current="page"':''} href="${L.href(file)}">${L.icon(ico)}${label}</a>`).join('')}</nav><div class="sidebar-foot"><div class="row"><span class="avatar">NI</span><span>Norte Ingeniería<br><span class="small muted" style="color:#a4bfb0">Empresa ficticia</span></span></div></div>`;
  const workspace=document.createElement('div');workspace.className='workspace';workspace.innerHTML=`<a class="skip-link" href="#page">Saltar al contenido</a><header class="topbar"><div class="row"><button class="btn ghost mobile-menu" id="menu-toggle" aria-label="Abrir navegación" aria-expanded="false">${L.icon('menu')}</button><div class="context"><strong id="project-context">${L.escape(p?.name||'Nuevo proyecto')}</strong>Expediente privado · <span id="role-context">${document.body.dataset.role==='supplier'?'Vista del proveedor':document.body.dataset.role==='field'?'Equipo en obra':'Equipo de ingeniería'}</span></div></div><div class="top-actions"><nav class="variant-picker" aria-label="Variante funcional">${Object.entries(vNames).map(([v,n])=>`<a href="${L.href(L.page(),{v})}" class="${L.variant()===v?'selected':''}" ${L.variant()===v?'aria-current="true"':''}>${n}</a>`).join('')}</nav><button class="btn ghost small" id="reset-demo" title="Restablecer todos los datos ficticios">${L.icon('refresh')}<span>Reiniciar</span></button></div></header><div class="demo-ribbon"><span>PROTOTIPO LOCAL · Datos ficticios · Servicios simulados</span><span class="ribbon-extra">USD de ejemplo, neto sin IVA · <a href="${L.href('index.html')}">Ver galería</a></span></div><main class="page-content"><div class="page-heading"><div><div class="eyebrow">${L.escape(document.body.dataset.sub||'Documentar · Decidir · Comprar · Ejecutar')}</div><h1>${L.escape(document.body.dataset.title||'Expediente eléctrico')}</h1><p class="subheading">${L.escape(document.body.dataset.description||'Cada decisión conserva su evidencia y su efecto en el proyecto.')}</p></div><div id="action-slot"></div></div><div id="state-banner"></div><div id="content-slot"></div></main><nav class="mobile-bottom" aria-label="Navegación móvil">${[['d-projects.html','project','Proyecto'],['d-engineering.html','plan','BOM'],['d-orders.html','order','Pedido'],['m-field.html','field','Obra']].map(([f,i,n])=>`<a href="${L.href(f)}">${L.icon(i)}${n}</a>`).join('')}</nav><div class="toast" id="toast" role="status" aria-live="polite"></div>`;
  sidebar.querySelector('nav').innerHTML=visibleNav.map(([file,ico,label])=>`<a class="nav-link ${L.page()===file?'active':''}" ${L.page()===file?'aria-current="page"':''} href="${L.href(file)}">${L.icon(ico)}${label}</a>`).join('');
  const roleSwitch=document.createElement('label');roleSwitch.className='demo-role-switch';roleSwitch.innerHTML=`Cambiar rol de demo<select aria-label="Cambiar rol de demo, sin autorización real"><option value="engineer" ${role==='engineer'?'selected':''}>Ingeniería</option><option value="supplier" ${role==='supplier'?'selected':''}>Proveedor</option><option value="field" ${role==='field'?'selected':''}>Obra</option></select>`;workspace.querySelector('.top-actions').append(roleSwitch);roleSwitch.querySelector('select').onchange=event=>location.href=L.href({engineer:'d-projects.html',supplier:'d-supplier.html',field:'m-field.html'}[event.target.value]);
  if(role==='supplier')workspace.querySelector('#project-context').textContent='Portal del proveedor';
  if(role==='supplier')sidebar.querySelector('.sidebar-foot').innerHTML='<div class="row"><span class="avatar">DE</span><span>Proveedor seleccionado<br><span class="small" style="color:#a4bfb0">Cuenta ficticia</span></span></div>';
  if(role!=='engineer')workspace.querySelector('.mobile-bottom').remove();
  document.body.prepend(sidebar);document.body.append(workspace);workspace.querySelector('#content-slot').append(page);if(act){act.id='act';workspace.querySelector('#action-slot').append(act);}
  workspace.querySelector('#menu-toggle').onclick=()=>{const open=sidebar.classList.toggle('open');workspace.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));};
  workspace.querySelector('#reset-demo').onclick=()=>{L.reset();L.toast('Demo reiniciada. La revisión técnica vuelve a estar pendiente.');};
  L.subscribe(()=>{const current=L.project();document.getElementById('project-context').textContent=role==='supplier'?'Portal del proveedor':current?.name||'Nuevo proyecto';});
  const state=new URLSearchParams(location.search).get('estado'),banner=document.getElementById('state-banner');
  // Las páginas de dominio ofrecen sus propios estados y vías de recuperación.
  banner.hidden=true;
  if(state==='error')banner.innerHTML=`<div class="notice error screen-error" role="alert"><strong>Servicio simulado no disponible.</strong> Los cambios guardados se conservan. <button class="btn small" id="state-retry">Reintentar localmente</button> <a href="${L.href('d-engineering.html')}" class="small">Continuar con revisión manual</a></div>`;
  if(state==='limit')banner.innerHTML=`<div class="notice warning screen-error"><strong>Escenario de límite.</strong> Las operaciones con consumo deben respetar el presupuesto. <a href="${L.href('d-operations.html')}" class="small">Ajustar presupuesto o usar vía manual</a><button class="btn small" id="state-retry">Volver al estado normal</button></div>`;
  if(state==='loading'){banner.innerHTML=`<div class="card screen-error" role="status"><strong>Preparando datos de la demo…</strong><div class="skeleton"></div><button class="btn small" id="state-retry">Omitir espera simulada</button></div>`;setTimeout(()=>banner.replaceChildren(),2000);}
  if(state==='empty')banner.innerHTML=`<div class="notice info screen-error">Vista de inicio: creá un proyecto, una solicitud o un pedido para avanzar. Los otros módulos conservan el expediente compartido. <button class="btn small" id="state-retry">Salir de la vista vacía</button></div>`;
  const retry=document.getElementById('state-retry');if(retry)retry.onclick=()=>{const url=new URL(location.href);url.searchParams.delete('estado');location.href=url;};
  const announceHeight=()=>parent.postMessage({type:'liard:height',height:document.documentElement.scrollHeight,page:L.page()},location.protocol==='file:'?'*':location.origin);
  new ResizeObserver(announceHeight).observe(document.body);announceHeight();
  window.addEventListener('liard:storage-error',()=>L.toast('El navegador restringe el almacenamiento en archivos. Usá el servidor local para persistir entre páginas.'));
});
